import type { Metadata } from "next";
import "@/css/globals.css";
import "@fontsource/inter/100.css";
import "@fontsource/inter/200.css";
import "@fontsource/inter/300.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "@fontsource/inter/700.css";
import "@fontsource/inter/800.css";
import "@fontsource/inter/900.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NextTopLoader from "nextjs-toploader";
import MobileNav from "@/components/MobileNav";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Gian’s Bus Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={` antialiased px-10 max-sm:px-4 min-[1440px]:px-[14vw] py-20`}>
        <NextTopLoader color="#0169b7" showSpinner={false} />
        <Navbar />
        <Suspense fallback={null}>
          <MobileNav />
        </Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
