import type { Metadata } from "next";
import "@/css/globals.css";
import "@fontsource/inter/100.css";
import "@fontsource/inter/200.css";
import "@fontsource/inter/300.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "@fontsource/inter/700.css";
import "@fontsource/inter/800.css";
import "@fontsource/inter/900.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NextTopLoader from "nextjs-toploader";
import MobileNav from "@/components/MobileNav";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Gian’s Bus Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <meta name="color-scheme" content="light" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const savedTheme = localStorage.getItem('theme') || 'blue';
                  const root = document.documentElement;
                  
                  switch (savedTheme) {
                    case 'green':
                      root.style.setProperty('--primary', '#0FC754');
                      root.style.setProperty('--cta-color', '#ffff');
                      break;
                    case 'orange':
                      root.style.setProperty('--primary', '#F9C048');
                      root.style.setProperty('--cta-color', '#1E1E1E');
                      break;
                    case 'red':
                      root.style.setProperty('--primary', '#FF2605');
                      root.style.setProperty('--cta-color', '#ffff');
                      break;
                    default:
                      root.style.setProperty('--primary', '#0169b7');
                      root.style.setProperty('--cta-color', '#ffff');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={` antialiased px-10 max-sm:px-4 min-[1440px]:px-[14vw] py-20 pb-8`}
      >
        <NextTopLoader color="var(--primary)" showSpinner={false} />
        <Navbar />
        <Suspense fallback={null}>
          <MobileNav />
        </Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
